//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.18063
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlueDwarf.Resources.Localization {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ConfigurationLocale {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ConfigurationLocale() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BlueDwarf.Resources.Localization.ConfigurationLocale", typeof(ConfigurationLocale).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Refresh interval:.
        /// </summary>
        public static string LocalProxyKeepaliveRefreshIntervalLabel {
            get {
                return ResourceManager.GetString("LocalProxyKeepaliveRefreshIntervalLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Local proxy keepalive.
        /// </summary>
        public static string LocalProxyKeepaliveTitle {
            get {
                return ResourceManager.GetString("LocalProxyKeepaliveTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Keepalive URL 1:.
        /// </summary>
        public static string LocalProxyKeepaliveURL1Label {
            get {
                return ResourceManager.GetString("LocalProxyKeepaliveURL1Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Keepalive URL 2:.
        /// </summary>
        public static string LocalProxyKeepaliveURL2Label {
            get {
                return ResourceManager.GetString("LocalProxyKeepaliveURL2Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Local proxy:.
        /// </summary>
        public static string LocalProxyLabel {
            get {
                return ResourceManager.GetString("LocalProxyLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Configure.
        /// </summary>
        public static string MenuConfigure {
            get {
                return ResourceManager.GetString("MenuConfigure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Exit.
        /// </summary>
        public static string MenuExit {
            get {
                return ResourceManager.GetString("MenuExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ....
        /// </summary>
        public static string PickRemoteProxy {
            get {
                return ResourceManager.GetString("PickRemoteProxy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à This is where you configure the local proxy for your browser and other applications.
        /// </summary>
        public static string ProxyServerConfigurationLegend {
            get {
                return ResourceManager.GetString("ProxyServerConfigurationLegend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Proxy server configuration.
        /// </summary>
        public static string ProxyServerConfigurationTitle {
            get {
                return ResourceManager.GetString("ProxyServerConfigurationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à This is where you go out.
        /// </summary>
        public static string ProxyTunnelConfigurationLegend {
            get {
                return ResourceManager.GetString("ProxyTunnelConfigurationLegend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Proxy tunnel configuration.
        /// </summary>
        public static string ProxyTunnelConfigurationTitle {
            get {
                return ResourceManager.GetString("ProxyTunnelConfigurationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Remote proxy:.
        /// </summary>
        public static string RemoteProxyLabel {
            get {
                return ResourceManager.GetString("RemoteProxyLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Find happiness at.
        /// </summary>
        public static string RemoteProxySite {
            get {
                return ResourceManager.GetString("RemoteProxySite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à s.
        /// </summary>
        public static string s {
            get {
                return ResourceManager.GetString("s", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à SOCKS 4 proxy server port:.
        /// </summary>
        public static string Socks4ServerPort {
            get {
                return ResourceManager.GetString("Socks4ServerPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Bytes read:.
        /// </summary>
        public static string StatisticsBytesRead {
            get {
                return ResourceManager.GetString("StatisticsBytesRead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Bytes written:.
        /// </summary>
        public static string StatisticsBytesWritten {
            get {
                return ResourceManager.GetString("StatisticsBytesWritten", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Connections so far:.
        /// </summary>
        public static string StatisticsConnections {
            get {
                return ResourceManager.GetString("StatisticsConnections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Statistics.
        /// </summary>
        public static string StatisticsTitle {
            get {
                return ResourceManager.GetString("StatisticsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Test URL:.
        /// </summary>
        public static string TestURL {
            get {
                return ResourceManager.GetString("TestURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Summon the wizard!.
        /// </summary>
        public static string WizardInvoke {
            get {
                return ResourceManager.GetString("WizardInvoke", resourceCulture);
            }
        }
    }
}
