//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18063
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlueDwarf.Resources.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class HomeLocale {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal HomeLocale() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BlueDwarf.Resources.Localization.HomeLocale", typeof(HomeLocale).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration.
        /// </summary>
        public static string ConfigurationTitle {
            get {
                return ResourceManager.GetString("ConfigurationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh interval:.
        /// </summary>
        public static string LocalProxyKeepaliveRefreshIntervalLabel {
            get {
                return ResourceManager.GetString("LocalProxyKeepaliveRefreshIntervalLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local proxy keepalive.
        /// </summary>
        public static string LocalProxyKeepaliveTitle {
            get {
                return ResourceManager.GetString("LocalProxyKeepaliveTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keepalive URL 1:.
        /// </summary>
        public static string LocalProxyKeepaliveURL1Label {
            get {
                return ResourceManager.GetString("LocalProxyKeepaliveURL1Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keepalive URL 2:.
        /// </summary>
        public static string LocalProxyKeepaliveURL2Label {
            get {
                return ResourceManager.GetString("LocalProxyKeepaliveURL2Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local proxy:.
        /// </summary>
        public static string LocalProxyLabel {
            get {
                return ResourceManager.GetString("LocalProxyLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Associate.
        /// </summary>
        public static string MenuConfigure {
            get {
                return ResourceManager.GetString("MenuConfigure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string MenuExit {
            get {
                return ResourceManager.GetString("MenuExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pick....
        /// </summary>
        public static string PickRemoteProxy {
            get {
                return ResourceManager.GetString("PickRemoteProxy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is where you configure the local proxy for your browser and other applications.
        /// </summary>
        public static string ProxyServerConfigurationLegend {
            get {
                return ResourceManager.GetString("ProxyServerConfigurationLegend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proxy.
        /// </summary>
        public static string ProxyServerConfigurationTitle {
            get {
                return ResourceManager.GetString("ProxyServerConfigurationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is where you go out.
        /// </summary>
        public static string ProxyTunnelConfigurationLegend {
            get {
                return ResourceManager.GetString("ProxyTunnelConfigurationLegend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tunnel.
        /// </summary>
        public static string ProxyTunnelConfigurationTitle {
            get {
                return ResourceManager.GetString("ProxyTunnelConfigurationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remote proxy:.
        /// </summary>
        public static string RemoteProxyLabel {
            get {
                return ResourceManager.GetString("RemoteProxyLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find happiness at.
        /// </summary>
        public static string RemoteProxySite {
            get {
                return ResourceManager.GetString("RemoteProxySite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to s.
        /// </summary>
        public static string s {
            get {
                return ResourceManager.GetString("s", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SOCKS 4 proxy server port:.
        /// </summary>
        public static string Socks4ServerPort {
            get {
                return ResourceManager.GetString("Socks4ServerPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bytes read:.
        /// </summary>
        public static string StatisticsBytesRead {
            get {
                return ResourceManager.GetString("StatisticsBytesRead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bytes written:.
        /// </summary>
        public static string StatisticsBytesWritten {
            get {
                return ResourceManager.GetString("StatisticsBytesWritten", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connections so far:.
        /// </summary>
        public static string StatisticsConnections {
            get {
                return ResourceManager.GetString("StatisticsConnections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statistics.
        /// </summary>
        public static string StatisticsTitle {
            get {
                return ResourceManager.GetString("StatisticsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string StatusTitle {
            get {
                return ResourceManager.GetString("StatusTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test URL:.
        /// </summary>
        public static string TestURL {
            get {
                return ResourceManager.GetString("TestURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Blue Dwarf.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wizard....
        /// </summary>
        public static string WizardInvoke {
            get {
                return ResourceManager.GetString("WizardInvoke", resourceCulture);
            }
        }
    }
}
