//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18063
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlueDwarf.Resources.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class HomeWelcomeLocale {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal HomeWelcomeLocale() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BlueDwarf.Resources.Localization.HomeWelcomeLocale", typeof(HomeWelcomeLocale).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browser configuration: SOCKS proxy on.
        /// </summary>
        public static string LocalProxy {
            get {
                return ResourceManager.GetString("LocalProxy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local proxy (to go out):.
        /// </summary>
        public static string LocalProxyLabel {
            get {
                return ResourceManager.GetString("LocalProxyLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Now, change your browser settings in order to use the Blue Dwarf (you can also download a proxy switcher such as SwitchySharp)..
        /// </summary>
        public static string LocalProxyLegend {
            get {
                return ResourceManager.GetString("LocalProxyLegend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LocalProxy.
        /// </summary>
        public static string LocalProxySection {
            get {
                return ResourceManager.GetString("LocalProxySection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remote proxy (to bypass censorship):.
        /// </summary>
        public static string RemoteProxyLabel {
            get {
                return ResourceManager.GetString("RemoteProxyLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A tunnel has been configured for you, based on system audit. You can change it in the configuration section..
        /// </summary>
        public static string TunnelConfigurationLegend {
            get {
                return ResourceManager.GetString("TunnelConfigurationLegend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Here is the best solution for you to avoid any censorship..
        /// </summary>
        public static string TunnelLegend {
            get {
                return ResourceManager.GetString("TunnelLegend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tunnel.
        /// </summary>
        public static string TunnelSection {
            get {
                return ResourceManager.GetString("TunnelSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to the Blue Dwarf. Since this is your first use, your system was evaluated and your configuration set up..
        /// </summary>
        public static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }
    }
}
